### ISSUE TITLE
Delete account success message is in passive voice

### ISSUE THREAD

**Issue by felipefreitag** [seasonedcc/croods-auth#11]
It says "Successfully deleted". We should change to something in active voice like the other messages

**Comment by gustavoguichard** [comment]
This is in https://github.com/SeasonedSoftware/new-react-app, if you think this commit didn't solve it, please, reopen the issue there:
https://github.com/SeasonedSoftware/new-react-app/commit/957ef98854129d8abdccb62a8cef7359e8fab560
