### ISSUE TITLE
Option to get an updated currentUser (From our backend, not from global state)

### ISSUE THREAD

**Issue by giovanisleite** [seasonedcc/croods-auth#6]
It would be like a `disableCache: true` option

**Comment by felipefreitag** [comment]
I thought the cache was disabled by default

**Comment by felipefreitag** [comment]
@gustavoguichard ?

**Comment by giovanisleite** [comment]
> I thought the cache was disabled by default

For croods yes, but for the currentUser it is cached by default.

https://github.com/SeasonedSoftware/croods-auth/blob/master/src/useCurrentUser.js#L7-L9

**Comment by vractal** [comment]
I believe you could pass `cache: false`  in the options when calling the hook.. Perhaps we should  make the available options clearer in the docs

**Comment by gustavoguichard** [comment]
Good one, @vractal , this is a documentation issue =D
I'll leave this issue open until we make it clear in the docs

**Comment by felipefreitag** [comment]
Ok! This is something that appears all the time and is always tricky to catch. It would be good to have both cases (with and without cache) very explicit in the docs.

**Comment by gustavoguichard** [comment]
Just realized the [documentation](https://croods.netlify.com/docs/cauth-current-user) was already talking about `cache` but not in a sound way xD

**Comment by gustavoguichard** [comment]
@felipefreitag just updated the docs with this pitfall:
http://croods.netlify.com/docs/cauth-current-user#disable-the-user-cache

**Comment by felipefreitag** [comment]
> @felipefreitag just updated the docs with this pitfall:
> http://croods.netlify.com/docs/cauth-current-user#disable-the-user-cache

👍 
Maybe add an example to the docs of when that's needed? @giovanisleite the cache must be disabled whenever an endpoint changes the user, is that correct?

If that's the case, maybe something like this...
```
Important: the current user is cached by default. When a request changes the user, or if this is giving you trouble, use it disabling the cache like so:
```
