### ISSUE TITLE
Logout callback is not executed if the user is at an authorized page

### ISSUE THREAD

**Issue by giovanisleite** [seasonedcc/croods-auth#7]
When the user clicks on logout and he is in a `authorize` page, the component renders again (because the currentUser was erased) and goes to login with `?redirect_to=/page-that-he-was`.

When the currentUser info is used on the component, it gets an error, because the user was erased, but only this component is being rendered again (Not all the Auth chain).

**Comment by gustavoguichard** [comment]
@giovanisleite , we are probably going to remove the callback from `useSignOut` to stop encouraging it's usage. The solution you are looking for is changing your logout function to something like this:

```js
const [, signOut] = useSignOut()
const { success } = useFlash()
const logout = async () => {
    await navigate('/')
    await signOut()
    success('Successfully logged out')
}
```

**Comment by gustavoguichard** [comment]
@giovanisleite
Just updated the docs with:
http://croods.netlify.com/docs/cauth-sign-out#what-if-my-app-breaks-when-i-log-out
