### ISSUE TITLE
Validation error messages

### ISSUE THREAD

**Issue by giovanisleite** [seasonedcc/croods-auth#9]
These messages should be standardized.

![image](https://user-images.githubusercontent.com/11703235/59775387-81f3f580-9287-11e9-8fff-598c3be9451e.png)

Freitag suggests following the messages of [redux-form-validators](https://www.npmjs.com/package/redux-form-validators#documentation)

**Comment by gustavoguichard** [comment]
https://github.com/SeasonedSoftware/croods-auth/commit/32dc47724a88014263e3cdd44ee5501c75f3d2c1
